### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by MatthewMc123** [SuperMartijn642/ChunkLoaders#101]
Ive installed Chunkloaders-1.2.7 for forge and installed supermartijn642configlib-1.1.8 for forge and my game says Mod Chunkloaders requires supermartijn642configlib 1.1.0 or above, and Below 1.2.0 and says below currently supermartijn642configlib is not installed.

**Comment by MatthewMc123** [comment]
Im using version 1.20.1 btw

**Comment by SuperMartijn642** [comment]
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/eb81496a-1cf5-44f4-90c2-78ed007d0a76)
