### ISSUE TITLE
Minecraft does not render (ultimate) chunk loader with BSL shaders

### ISSUE THREAD

**Issue by uhloin** [SuperMartijn642/ChunkLoaders#104]
Minecraft 1.20.1
forge 47.1.76
chunkloaders-1.2.7-forge-mc1.20.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar 
supermartijn642corelib-1.1.12a-forge-mc1.20.jar 
embeddium-0.1.10+mc1.20.1.jar
oculus-mc1.20.1-1.6.9.jar
Shader: BSL_v8.2.04.zip

The same issue with older versions Rubidium/Oculus for 1.20.1.
BSL shaders are OK for blocks from other mods.

**Comment by SuperMartijn642** [comment]
> embeddium-0.1.10+mc1.20.1.jar
oculus-mc1.20.1-1.6.9.jar
Shader: BSL_v8.2.04.zip

It seems to be working fine with those mods and the BSL shader pack installed.
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/a2d81684-c42e-4d1f-a131-ae5eebe8dac1)
