### ISSUE TITLE
[Bug] ServerCore causes RandomTicks to not happen

### ISSUE THREAD

**Issue by CuddleTheif** [SuperMartijn642/ChunkLoaders#106]
**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, 1.2.8-fabric-mc1.20.1

**Are you using OptiFine?:** No

**Description of the Bug**
Cauldrons don't fill in chunkloaders when player not nearby

**Steps to Reproduce**
Dripstone with lava over it over cauldron.
Add chunk loader to chunk and set to load chunk.
Log off for a hour or more
Log back in and cauldron still empty

**Comment by SuperMartijn642** [comment]
Seems to work just fine

https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/aada538d-b4ac-4a68-b098-ff620d9d29cc

If it is not your server, the config options for inactivity timeout might have been changed. Server operators can change the time for a player to be offline after which their chunk loaders will be turned off.

**Comment by CuddleTheif** [comment]
My bad. After extenstive testing I found out it is a compatibility issue with [ServerCore](https://modrinth.com/mod/servercore) Mod. Seems when ServerCore is installed along side ChunkLoaders random ticks do not happen at all in chunks staying loaded by ChunkLoaders (Though the chunks are still loaded otherwise).

**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, 1.2.8-fabric-mc1.20.1
- ServerCore, 1.3.7+1.20.1

**Steps to Reproduce**
Install only ChunkLoaders and ServerCore. 
Create new world
set randomTick to 0
plant crops
save cords
tp 1000+ blocks away
set randomTick to 1000
wait a couple min
set randomTick to 0
tp back to spawn
Plants will not have grown

**Comment by SuperMartijn642** [comment]
Could you also report the issue to ServerCore? I haven't yet looked into why this happens, but maybe they will already know and know how to fix it.

**Comment by SuperMartijn642** [comment]
This was an issue with ServerCore and has since been fixed (https://github.com/Wesley1808/ServerCore/issues/95).
