### ISSUE TITLE
[Bug] Chunkloaders stop loading the world after server restart.

### ISSUE THREAD

**Issue by SabrCat** [SuperMartijn642/ChunkLoaders#107]
**Version Info**
- Minecraft, 1.19.2 fabric
- Chunk Loaders, 1.2.8

**Are you using OptiFine?:** no

**Description of the Bug**
A chunkloader placed down will load it's chunks successfully. However, after a server restart the same chunks are no longer being loaded, not even when a player enters the area of the chunk loaders and leaves again. The UI of the chunk loader still displays the chunks as loaded, even though they are not. Chunk loader expiry time is set to -1 in the settings.

**Steps to Reproduce**
1) Place a chunk loader and select chunks to load
2) Place a command block that continuously says test
3) Move away and see the messages keep coming
4) Restart the server
5) The messages now only appear when a player is loading the command block

**Screenshots**
<details>
  <summary>expand this</summary>

Status quo on the server: The chunks are not loaded even though they show up as loaded in the UI
![2023-10-20_20 15 16](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/e0fd7fff-6c3d-45cd-8943-0a355d93e07b)
![2023-10-20_20 15 20](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/aee4f8bb-9cb9-4d0e-98a4-0f2b384eb042)
![2023-10-20_20 15 41](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/935ae44c-c5c5-4762-9280-6f4a99a3386f)
I removed the chunk loader, placed it again and re-selected the chunks. 
![2023-10-20_20 16 24](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/8e25eb8f-cdd2-4fb0-b29e-d3c4706918db)
And it worked successfully when I moved away
![2023-10-20_20 16 39](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/42d26368-9258-4b80-9be0-cca2cb31c406)
I then restarted the server, and it ceased to work again. 
![2023-10-20_20 20 14](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/70419a93-c95a-4b5a-878e-5a9c87e6ac8a)
![2023-10-20_20 20 39](https://github.com/SuperMartijn642/ChunkLoaders/assets/56313836/3d1c84c2-0b4c-4662-902f-ee05d2996082)

</details>
  

<details>
  <summary>Mod List</summary>

**Server Side**
```
[20:18:56] [main/INFO]: Loading 178 mods:
        - adventure-platform-fabric 5.5.1
           |-- net_kyori_adventure-api 4.12.0
           |-- net_kyori_adventure-key 4.12.0
           |-- net_kyori_adventure-platform-api 4.1.2
           |-- net_kyori_adventure-text-logger-slf4j 4.12.0
           |-- net_kyori_adventure-text-minimessage 4.12.0
           |-- net_kyori_adventure-text-serializer-gson 4.12.0
           |-- net_kyori_adventure-text-serializer-plain 4.12.0
           |-- net_kyori_examination-api 1.3.0
           \-- net_kyori_examination-string 1.3.0
        - aileron 1.19-1.0.2
        - architectury 6.5.85
        - balm-fabric 4.6.0
        - betterstats 2.9.3+1.19.2
           \-- tcdcommons 2.9.1+1.19.2
        - carpet 1.4.84
        - carpet-fixes 1.19-1.12.2
           \-- conditional-mixin 0.3.1
        - chunkloaders 1.2.8
        - chunkpregen 0.3.3
        - cloth-config 8.3.103
           \-- cloth-basic-math 0.6.1
        - create 0.5.1-c-build.1160+mc1.19.2
           |-- com_google_code_findbugs_jsr305 3.0.2
           |-- flywheel 0.6.9-6
           |-- forge_tags 3.0
           |-- milk 1.0.51
           |    \-- dripstone_fluid_lib 2.0.1
           |-- porting_lib_accessors 2.1.1096+1.19.2
           |-- porting_lib_base 2.1.1096+1.19.2
           |    |-- mm 2.3
           |    |-- porting_lib_attributes 2.1.1096+1.19.2
           |    |-- porting_lib_common 2.1.1096+1.19.2
           |    |-- porting_lib_constants 2.1.1096+1.19.2
           |    |-- porting_lib_lazy_registration 2.1.1096+1.19.2
           |    |-- porting_lib_loot 2.1.1096+1.19.2
           |    |-- porting_lib_model_generators 2.1.1096+1.19.2
           |    |-- porting_lib_model_loader 2.1.1096+1.19.2
           |    |-- porting_lib_models 2.1.1096+1.19.2
           |    \-- serialization_hooks 0.3.26
           |-- porting_lib_entity 2.1.1096+1.19.2
           |    \-- porting_lib_constants 2.1.1096+1.19.2
           |-- porting_lib_extensions 2.1.1096+1.19.2
           |    |-- porting_lib_attributes 2.1.1096+1.19.2
           |    |-- porting_lib_common 2.1.1096+1.19.2
           |    \-- porting_lib_constants 2.1.1096+1.19.2
           |-- porting_lib_fake_players 2.1.1096+1.19.2
           |-- porting_lib_networking 2.1.1096+1.19.2
           |-- porting_lib_obj_loader 2.1.1096+1.19.2
           |    |-- porting_lib_attributes 2.1.1096+1.19.2
           |    |-- porting_lib_common 2.1.1096+1.19.2
           |    |-- porting_lib_constants 2.1.1096+1.19.2
           |    \-- porting_lib_model_loader 2.1.1096+1.19.2
           |-- porting_lib_transfer 2.1.1096+1.19.2
           |    |-- porting_lib_attributes 2.1.1096+1.19.2
           |    |-- porting_lib_common 2.1.1096+1.19.2
           |    \-- porting_lib_constants 2.1.1096+1.19.2
           |-- reach-entity-attributes 2.3.0
           \-- registrate-fabric 1.1.58-MC1.19.2
        - create-track-map 1.4
        - create_enchantment_industry 1.0.1.b
           \-- create_dragon_lib 1.0.1
        - create_jetpack 3.3.1
           \-- flightlib 1.1.0
        - createaddition 20230723a
           \-- team_reborn_energy 2.3.0
        - createdeco 1.3.3-1.19.2
        - creategoggles 0.5.5.e
        - debugify 2.8.0
        - dimensional-inventories 1.0.2+1.19.2
        - dynmap 3.6
        - emi 1.0.22+1.19.2+fabric
        - emi_loot 0.6.5+1.19
        - emiffect 0.1.5+mc1.19.2
        - extra-mod-integrations 0.1.2+1.19.2
        - fabric-api 0.76.1+1.19.2
           |-- fabric-api-base 0.4.15+8f4e8eb390
           |-- fabric-api-lookup-api-v1 1.6.14+93d8cb8290
           |-- fabric-biome-api-v1 9.1.1+16f1e31390
           |-- fabric-block-api-v1 1.0.2+e415d50e90
           |-- fabric-blockrenderlayer-v1 1.1.25+cafc6e8e90
           |-- fabric-client-tags-api-v1 1.0.5+b35fea8390
           |-- fabric-command-api-v1 1.2.16+f71b366f90
           |-- fabric-command-api-v2 2.2.1+413cbbc790
           |-- fabric-commands-v0 0.2.33+df3654b390
           |-- fabric-containers-v0 0.1.42+df3654b390
           |-- fabric-content-registries-v0 3.5.2+7c6cd14d90
           |-- fabric-convention-tags-v1 1.3.0+4bc6e26290
           |-- fabric-crash-report-info-v1 0.2.8+aeb40ebe90
           |-- fabric-data-generation-api-v1 5.3.9+413cbbc790
           |-- fabric-dimensions-v1 2.1.35+0d0f210290
           |-- fabric-entity-events-v1 1.5.4+9244241690
           |-- fabric-events-interaction-v0 0.4.34+562bff6e90
           |-- fabric-events-lifecycle-v0 0.2.36+df3654b390
           |-- fabric-game-rule-api-v1 1.0.24+b6b6abb490
           |-- fabric-item-api-v1 1.6.6+b7d1888890
           |-- fabric-item-groups-v0 0.3.39+9244241690
           |-- fabric-key-binding-api-v1 1.0.25+5c4fce2890
           |-- fabric-keybindings-v0 0.2.23+df3654b390
           |-- fabric-lifecycle-events-v1 2.2.4+1b46dc7890
           |-- fabric-loot-api-v2 1.1.13+83a8659290
           |-- fabric-loot-tables-v1 1.1.16+9e7660c690
           |-- fabric-message-api-v1 5.0.7+93d8cb8290
           |-- fabric-mining-level-api-v1 2.1.24+33fbc73890
           |-- fabric-models-v0 0.3.21+c6af733c90
           |-- fabric-networking-api-v1 1.2.12+def3f86d90
           |-- fabric-networking-v0 0.3.29+df3654b390
           |-- fabric-object-builder-api-v1 4.2.2+d8ef690890
           |-- fabric-particles-v1 1.0.14+4d0d570390
           |-- fabric-recipe-api-v1 1.0.2+413cbbc790
           |-- fabric-registry-sync-v0 0.9.33+9244241690
           |-- fabric-renderer-api-v1 1.2.1+1adbf27790
           |-- fabric-renderer-indigo 0.8.0+1adbf27790
           |-- fabric-renderer-registries-v1 3.2.24+df3654b390
           |-- fabric-rendering-data-attachment-v1 0.3.19+6e0787e690
           |-- fabric-rendering-fluids-v1 3.0.11+4d0d570390
           |-- fabric-rendering-v0 1.1.27+df3654b390
           |-- fabric-rendering-v1 1.12.1+d8ef690890
           |-- fabric-resource-conditions-api-v1 2.1.2+aae9039d90
           |-- fabric-resource-loader-v0 0.8.4+edbdcddb90
           |-- fabric-screen-api-v1 1.0.32+4d0d570390
           |-- fabric-screen-handler-api-v1 1.3.8+1cc24b1b90
           |-- fabric-sound-api-v1 1.0.2+c4f28df590
           |-- fabric-textures-v0 1.0.24+aeb40ebe90
           |-- fabric-transfer-api-v1 2.1.6+413cbbc790
           \-- fabric-transitive-access-wideners-v1 1.3.3+08b73de490
        - fabric-language-kotlin 1.10.10+kotlin.1.9.10
           |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
           |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
        - fabricloader 0.14.22
        - farmersdelight 1.19.2-1.3.10.1
        - ferritecore 5.0.3
        - inventoryessentials 5.4.0
        - inventorymanagement 1.1.2
           \-- roundalib 0.2.1
        - jade 8.7.3
        - jadeaddons 3.2.0
        - java 17
        - journeymap 5.9.7
           \-- journeymap-api-fabric 1.19.1-1.9-fabric-SNAPSHOT
        - lazydfu 0.1.3
        - lithium 0.11.1
        - memoryleakfix 1.1.2
           \-- com_github_llamalad7_mixinextras 0.2.0-beta.8
        - minecraft 1.19.2
        - mixin-conflict-helper 1.2.0
        - mixintrace 1.1.1+1.17
        - multiworld-bundle bundle
           \-- multiworld 1.7
                \-- fantasy 0.4.10+1.19.2
        - nochatreports 1.19.2-v1.13.12
           |-- fabric-rendering-v1 1.11.0+73145abb90
           \-- fabric-screen-api-v1 1.0.27+93d8cb8290
        - railways 1.5.1+fabric-mc1.19.2
           \-- mm 2.3
        - reputation 0.2.2+jade.1.19
        - shulkerboxtooltip 3.2.2+1.19.2
        - sliceanddice 2.3.2
           \-- forgeconfigapiport 4.2.11
                |-- com_electronwill_night-config_core 3.6.5
                \-- com_electronwill_night-config_toml 3.6.5
        - smoothboot 1.19-1.7.1
        - sound_physics_remastered 1.19.2-1.2.1
        - starlight 1.1.1+fabric.ae22326
        - supermartijn642configlib 1.1.8+a
        - supermartijn642corelib 1.1.15
        - tabtps-fabric 1.3.15
           |-- cloud 1.8.0-SNAPSHOT
           |    |-- cloud_commandframework_cloud-brigadier_ 1.8.0-SNAPSHOT
           |    |-- cloud_commandframework_cloud-core_ 1.8.0-SNAPSHOT
           |    |-- cloud_commandframework_cloud-services_ 1.8.0-SNAPSHOT
           |    |-- fabric-permissions-api-v0 0.1-SNAPSHOT
           |    \-- io_leangen_geantyref_geantyref 1.3.13
           |-- cloud_commandframework_cloud-minecraft-extras 1.8.0-SNAPSHOT
           |-- com_typesafe_config 1.4.2
           |-- net_kyori_adventure-serializer-configurate4 4.11.0
           |-- net_kyori_adventure-text-feature-pagination 4.0.0-SNAPSHOT
           |-- net_kyori_adventure-text-serializer-legacy 4.11.0
           |-- org_spongepowered_configurate-core 4.1.2
           \-- org_spongepowered_configurate-hocon 4.1.2
        - textile_backup 2.5.0-1.19
           |-- com_github_shevek_parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
           |-- org_apache_commons_commons-compress 1.21
           \-- org_tukaani_xz 1.9
        - universal-graves 2.1.3+1.19.2
           |-- common-protection-api 1.0.0
           |-- fabric-permissions-api-v0 0.1-SNAPSHOT
           |-- hologram-api 0.2.2+1.19
           |-- placeholder-api 2.0.0-pre.1+1.19.2
           |-- polymer 0.2.17+1.19.2
           |    |-- packet_tweaker 0.3.0+1.18.2
           |    \-- polymer-registry-sync-manipulator 0.0.3+1.19.2
           |-- server_translations_api 1.4.18+1.19.2
           |    \-- packet_tweaker 0.3.0+1.18.2
           \-- sgui 1.1.5+1.19.1
        - voicechat 1.19.2-2.4.26
           \-- fabric-key-binding-api-v1 1.0.18+9ff28f4095
        - worldedit 7.2.12+6240-87f4ae1
        - yet-another-config-lib 2.2.0-for-1.19.2
        - yosbr 0.1.2
```

**Client Side**
  [✔] advancementinfo-1.19.1-fabric0.58.5-1.3.1
  [✔] aileron-1.19-fabric-1.0.2
  [✔] animatica-0.5+1.19
  [✔] antighost-1.19.1-fabric0.58.5-1.1.5
  [✔] architectury-6.5.85-fabric
  [✔] balm-fabric-1.19.2-4.6.0
  [✘] BetterF3-4.0.0-Fabric-1.19.2.jar (disabled)
  [✔] bettermounthud-1.2.0
  [✔] betterstats-2.9.3+1.19.2
  [✔] borderless-mining-1.1.5+1.19
  [✔] capes-1.5.2+1.19.2-fabric
  [✔] carpet-fixes-1.19-1.12.2
  [✘] cem-0.7.3-1.19.jar (disabled)
  [✔] chat_heads-0.10.22-fabric-1.19.2
  [✔] chunkloaders-1.2.8-fabric-mc1.19.2
  [✔] CITResewn-1.1.2+1.19.2
  [✔] cloth-config-8.3.103-fabric
  [✔] colormatic-3.1.2+mc.1.19
  [✔] continuity-2.0.2+1.19
  [✔] Controlling-fabric-1.19.2-10.0+7
  [✔] create_enchantment_industry-1.0.1.b
  [✔] create_jetpack-fabric-3.3.1
  [✔] createaddition-fabric+1.19.2-20230723a
  [✔] createdeco-1.3.3-1.19.2
  [✔] create-fabric-0.5.1-c-build.1160+mc1.19.2
  [✔] creategoggles-1.19.2-0.5.5.e-[FABRIC]
  [✘] create-track-map-1.4+mc1.19.2-fabric-create-0.5.1.jar (disabled)
  [✔] CullLessLeaves-1.0.6
  [✔] Debugify-2.8.0
  [✔] DistantHorizons-1.6.9a-1.19.2
  [✔] double_hotbar-1.19-v1.2.3
  [✔] dynamic-fps-3.2.1+minecraft-1.19.0
  [✔] emi_loot-0.6.5+1.19
  [✔] emi-1.0.22+1.19.2+fabric
  [✔] emicompat-2.0.3
  [✔] emiffect-0.1.5+mc1.19.2
  [✔] EMITrades-fabric-1.0.2+mc1.19.2
  [✔] enhancedblockentities-0.7.2+1.19.2
  [✔] entity_model_features_fabric_1.19.2-1.0.2
  [✔] entity_texture_features_fabric_1.19.2-4.5.1
  [✔] entityculling-fabric-1.6.1-mc1.19.2
  [✘] extendedbogeys-0.4.7-1.19.2-0.5.1.cfabric-patch-.jar (disabled)
  [✔] extra-mod-integrations-0.1.2+1.19.2
  [✔] fabric-api-0.76.1+1.19.2
  [✔] fabric-carpet-1.19.2-1.4.84+v221018
  [✘] fabric-chunkpregen-0.3.5.jar (disabled)
  [✔] fabric-language-kotlin-1.10.10+kotlin.1.9.10
  [✔] fabricskyboxes-0.7.2+mc1.19.2
  [✔] fabrishot-1.9.2
  [✔] farmers-delight-fabric-mc1.19-1.19.2-1.3.10.1-bytecode-patch
  [✔] farsight-fabric-1.19-2.4
  [✔] ferritecore-5.0.3-fabric
  [✔] freecam-modrinth-1.1.6+1.19
  [✔] fsb-interop-1.3.2+mc1.19.2-build.40
  [✔] indium-1.0.9+mc1.19.2
  [✔] inventoryessentials-fabric-1.19.2-5.4.0
  [✔] inventorymanagement-1.1.2+1.19
  [✔] iris-flywheel-compat-1.19.2-0.2.1
  [✔] iris-mc1.19.2-1.6.9
  [✔] item-model-fix-1.0.3+1.19
  [✔] Jade-1.19.1-fabric-8.7.3
  [✔] JadeAddons-1.19.2-fabric-3.2.0
  [✔] journeymap-1.19.2-5.9.7-fabric
  [✔] lambdabettergrass-1.3.0+1.19
  [✔] lambdynamiclights-2.2.0+1.19.2
  [✔] language-reload-1.5.9+1.19.2
  [✔] lazydfu-0.1.3
  [✔] lithium-fabric-mc1.19.2-0.11.1
  [✔] main-menu-credits-1.1.1
  [✔] malilib-fabric-1.19.2-0.13.0
  [✔] memoryleakfix-fabric-1.17+-1.1.2
  [✔] midnightcontrols-1.7.4+1.19
  [✔] MixinConflictHelper-1.2.0
  [✔] mixintrace-1.1.1+1.17
  [✘] mod-loading-screen-1.0.3.jar (disabled)
  [✔] modmenu-4.2.0-beta.2
  [✔] morechathistory-1.19.1-1.1.1
  [✔] NoChatReports-FABRIC-1.19.2-v1.13.12
  [✔] nofade-1.18-2.0.1
  [✔] optigui-2.1.5
  [✔] puzzle-1.4.2-1.19
  [✔] reeses_sodium_options-1.6.4+mc1.19.2-build.93
  [✔] shulkerboxtooltip-fabric-3.2.2+1.19.2
  [✔] sliceanddice-fabric-2.3.2
  [✔] smoothboot-fabric-1.19-1.7.1
  [✔] sodium-extra-0.4.16+mc1.19.2-build.90
  [✔] sodium-fabric-mc1.19.2-0.4.4+build.18
  [✔] soundphysics-fabric-1.19.2-1.2.1
  [✔] starlight-1.1.1+fabric.ae22326
  [✔] Steam_Rails-1.5.1+fabric-mc1.19.2
  [✔] supermartijn642configlib-1.1.8a-fabric-mc1.19
  [✔] supermartijn642corelib-1.1.15-fabric-mc1.19.2
  [✔] textile_backup-2.5.0-1.19
  [✔] tweakeroo-fabric-1.19.2-0.14.3
  [✔] voicechat-fabric-1.19.2-2.4.26
  [✔] WorldEditCUI-1.19.2+01
  [✔] worldedit-mod-7.2.12
  [✔] YetAnotherConfigLib-2.2.0-for-1.19.2
  [✔] yosbr-0.1.2
  [✔] your-reputation-0.2.2+jade.1.19
  [✔] Zoomify-2.9.0 
  </details>
  
  Thanks in advance for help!
  
  Edit: It may be important to point out that we are running Multiworld, which adds a new dimension that appears to work just like a data pack created custom dimension. These tests were done in that custom dimension, which is a creative testing world separate from the survival server. Both share the same seed.

**Comment by SuperMartijn642** [comment]
The chunks which should be loaded by chunk loaders get initialized after the spawn area has been loaded. This works fine for vanilla's dimensions and custom datapack dimensions as those get loaded right before the spawn area gets loaded.

Multiworld seems to load its dimensions a bit later on, thus when the chunks which should be loaded by chunk loaders get initialized the dimensions aren't there yet.

In Chunk Loaders version 1.2.8a for Fabric, I have now reworked the loading a bit so it should work for any dimensions. In case you still encounter issues, of course let me know.
Thank you for reporting the issue!
