### ISSUE TITLE
no mobs spawn out of spawners

### ISSUE THREAD

**Issue by GreenForzeGaming** [SuperMartijn642/ChunkLoaders#108]
**Version Info**
- Minecraft, ... 1.20.1
- Chunk Loaders, ... 1.2.8

**Are you using OptiFine?:** ... no

**Description of the Bug**
... no mobs spawn from spawners in loaded chunk

**Steps to Reproduce**
... casual gameplay

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Mob spawners are only active if there's a player within 24 blocks range. It has nothing to do with chunk loading 🤔
