### ISSUE TITLE
[Bug] basic chunk loader doesn't work Minecraft, ...1.20.1

### ISSUE THREAD

**Issue by BloodInAs** [SuperMartijn642/ChunkLoaders#109]
**Version Info**
- Minecraft, ...1.20.1
- Chunk Loaders, ...chunkloaders-1.2.7-forge-mc1.20

**Description of the Bug**
The configuration of chunks in the loader gets lost when teleporting from the normal world to an additional world (for example, hell). It’s impossible to reconfigure, you have to break it and reinstall it)

**Screenshots**
... https://www.youtube.com/watch?v=3w7rGoIOGFA&ab_channel=DariaEfremova

**Comment by SuperMartijn642** [comment]
This should already be fixed. Please update Chunk Loaders.
