### ISSUE TITLE
Problem with building it.

### ISSUE THREAD

**Issue by PandaPandur** [SuperMartijn642/ChunkLoaders#11]
Hey! I got a problem with the mod and I don't know what I've done incorrect but I installed the package correctly and when I try to build it on my Server I can't for any reason. It doesn't show me the ChunkLoader. I got the Mod installed on my Server Plugins but it still won't work.

**Comment by SuperMartijn642** [comment]
Chunk Loaders is a Forge mod, do you have Forge installed on your server?

What do you mean by 'built it', crafting?

**Comment by PandaPandur** [comment]
Yeah we couldn‘t craft it and I didn‘t know we would need Forge for it. Is that all we would need for it?

**Comment by SuperMartijn642** [comment]
Well, Chunk Loaders is listed under 'mods' on CurseForge, not under 'plugins'.
You need both Forge and Config Lib.

**Comment by PandaPandur** [comment]
Ok. I’ll try it out later and answer wether it went good or not. Thanks btw
