### ISSUE TITLE
[Question] Multidimension Chunk Loaders

### ISSUE THREAD

**Issue by PedroCavaleiro** [SuperMartijn642/ChunkLoaders#112]
**Question**
Is it possible to place a Chunk Loader in the Nether another in the Overworld keep a scarecrow on the usual AFK spot for the mob farm and keep everything working on both sides?

**Comment by SuperMartijn642** [comment]
Chunk loaders will simply keep the chunks loaded which you select in the gui. Which dimension the chunk loader is placed doesn't affect that.
