### ISSUE TITLE
Chunk Loaders not loading chunks

### ISSUE THREAD

**Issue by NoodlesAreYummy1199** [SuperMartijn642/ChunkLoaders#113]
1.20.4, Fabric 1.20.4, Chunk Loaders 1.2.8a, Supermartijin642lib core and the other thing i forgor what it called
- Minecraft, Java
- Chunk Loaders, 1.2.8a

**Are you using OptiFine?:** Yes

**Description of the Bug**
Chunk loaders doesnt work when the chunk gets unloaded after i place the chunk loader and load the chunk

**Steps to Reproduce**
Place the chunk loader and load the chunk

**Screenshots**
idk how to screenshot this

**Comment by WaviestBalloon** [comment]
Having the same issue, after leaving the server, machines or crops inside of chunks do not progress.
I am not using OptiFine, using NeoForged version.

**Comment by brisingraerowing** [comment]
I'm running into similar issues on 1.12.2, though when having a chunk loaded in one dimension while being in another. The chunk loader does absolutely nothing when I'm not in its dimension. This makes using things like AE2 in the Random Things spectre dimension impossible while not being there.

**Comment by nojomyth-dev** [comment]
Any updates on this? I currently only can load chunks if i use /forceload, which allows for random ticking due to the chunkloader but is not quite ideal

**Comment by invaderxan1** [comment]
Is this mod dead? I am also having this issue, months later

**Comment by SuperMartijn642** [comment]
It seems to work fine with just Chunk Loaders (+ dependencies) installed:

https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/1a0eb5b0-acba-43db-8a6e-7a5b51456249

For anyone encountering the issue **on Fabric 1.20.3 or 1.20.4**:
Are you using any other mods? If so, could you narrow down which other mods are needed to reproduce the issue?
Are there any particular steps to reproduce the issue?

If you are playing on a different Minecraft version or using a different modloader, please create a separate issue.

> I'm running into similar issues on 1.12.2, though when having a chunk loaded in one dimension while being in another.

@brisingraerowing what you describe is different from what is reported in this issue. If you are still encountering problems, please create a separate issue.
