### ISSUE TITLE
[Bug] [1.20.1][SMP] Stop chunk loading after some days

### ISSUE THREAD

**Issue by ptk2003** [SuperMartijn642/ChunkLoaders#114]
**Version Info**
- Minecraft, 1.20.1
- Forge, 47.2.19
- Chunk Loaders, 1.2.8a
- Also:
  - supermartijn642corelib-1.1.16-forge-mc1.20.1.jar
  - supermartijn642configlib-1.1.8-forge-mc1.20.jar

**Are you using OptiFine?:** No

**Description of the Bug**
selected and "loaded" chunks are unloading when i logoff from server

**Steps to Reproduce**
craft and place chunkloader, open GUI, select chunks to load, ... wait some days..., found that chunks no more loading without any player.
replace block and recheck chunks to load not solve the problem.

set inactivityTimeout = -1 not solve too

**Screenshots**
...

**Comment by ptk2003** [comment]
caused by The-Hordes
after update to The-Hordes-1.20.1-1.3.2a it stop work chunkloaders

**Comment by SuperMartijn642** [comment]
Chunk Loading on Forge is handled through Forge's API. If it no longer works with The-Hordes installed, they are likely breaking Forge's API. Please report the issue to them.
