### ISSUE TITLE
Self remove after x days

### ISSUE THREAD

**Issue by Reaviik** [SuperMartijn642/ChunkLoaders#116]
Would it be possible to make the chunk load destroy itself after x days? a true/false setting would be very useful for servers

**Comment by SuperMartijn642** [comment]
I feel like that would be very annoying, having to replace all chunk loaders every x days.
I also don't really see how that would be useful for servers 🤔

**Comment by Reaviik** [comment]
Honestly, I don't know if I can do this, but as the number of pieces loaded on a server tends to reduce its TPS, this would be a resource for those who emphasize hosting maintenance, which is not cheap at all.

This is a common division for me, because I never find the terms of use.

**Comment by SuperMartijn642** [comment]
I have no clue what your last comment means.

If you want to reduce the number of loaded chunks on servers, Chunk Loaders already has an inactivity timeout config option. If you set it, someone's chunks will not be loaded after they've been offline for x amount of time.

**Comment by Reaviik** [comment]
I understand. I will try to adapt to this.

sorry grammar, I'm using google translate. thank you reply
