### ISSUE TITLE
[Bug]   Entities and block entities stop working in the loaded chunks while the player is in another dimension

### ISSUE THREAD

**Issue by Eltosergi** [SuperMartijn642/ChunkLoaders#119]
**Version Info**
- Minecraft, 1.20.4 fabric
- Chunk Loaders, 1.2.8a

**Are you using OptiFine?:** no

**Description of the Bug**
entities and block entities stop working in the loaded chunks while the player is in another dimension, farms such as iron farms stop working while you are in another dimension, just like block entities such as furnaces or brewing stands

**Screenshots**
![Screenshot 2024-04-10 00-17-33](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/34ecd19b-8186-484c-b234-5ce99f0fa84b)
![Screenshot 2024-04-10 00-18-05](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/a5f2c69c-9a2a-42ba-b99c-0d60e9ef75d1)
![Screenshot 2024-04-10 00-20-55](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/c61b7371-e111-472d-8138-3f75d0211016)
![Screenshot 2024-04-10 00-18-49](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/043c4c3c-5c3d-4fd0-a59d-a46063ba28cd)
![Screenshot 2024-04-10 00-20-03](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/1e83b04d-9a34-4e46-aa9c-645c6d7b2d9e)
![Screenshot 2024-04-10 00-21-15](https://github.com/SuperMartijn642/ChunkLoaders/assets/101887674/646a7310-ebdf-4c39-bb3a-ce46eacd1e93)

**Comment by Eltosergi** [comment]
It is a problem with the current version (1.20.4, 1.20.3), previous versions still work correctly.
If you want the entities and block entities to work when they are in another dimension, use version 1.20.2.

**Comment by SuperMartijn642** [comment]
It seems to work fine with just Chunk Loaders (+ dependencies) installed:

https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/1a0eb5b0-acba-43db-8a6e-7a5b51456249

Are you using any other mods? If so, could you narrow down which other mods are needed to reproduce the issue?
