### ISSUE TITLE
[Feature] Custom GUI scale

### ISSUE THREAD

**Issue by rwtallant13** [SuperMartijn642/ChunkLoaders#12]
I would like an option to scale the size of the chunk selector in the config file and not have it tie itself to the games GUI scale.

**Comment by SuperMartijn642** [comment]
Why do you want a separate setting for it?

**Comment by rwtallant13** [comment]
I like to keep my game scale smaller so the items on screen take up less space, but doing that makes the scale for the chunkloader too small to see what it shows well.

**Comment by DaniloNocete** [comment]
i loved the mod, but my gui is small too and i can't see exactly what is happening .-.

**Comment by SuperMartijn642** [comment]
Chunk Loaders 1.2.0 changes the gui completely, so this should no longer be relevant.
