### ISSUE TITLE
[Bug] Mobs from spawner using Apotheosis and chunkloader not spawning when far from spawner

### ISSUE THREAD

**Issue by mystikKey** [SuperMartijn642/ChunkLoaders#120]
**Version Info**
- Minecraft 1.20.1, Forge 47.2.23
- Chunk Loaders 1.2.8a
- Apotheosis 7.3.5

**Are you using OptiFine?:** 
No

**Description of the Bug**
Mobs don't spawn from mob spawner when away from chunk despite using Apotheosis mod with a "ignore player" spawner and chunk loader with 3x3 chunk loaded

**Steps to Reproduce**
- Place spawner with zombie piglin (for example)
- Right click with nether star (ignores player) and dragon egg (ignore conditions)
- Right click with sugar and clock to speedup spawn
- Place 3*3 chunk loader and go 10 chunks away for example

**Screenshots**
No screenshots

**Comment by SuperMartijn642** [comment]
Can you check that mobs spawn when using the vanilla `/forceload` command to load the chunk rather than a chunk loader?
