### ISSUE TITLE
[Bug] Chunkloaders need to be started manually when servercore is installed

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/ChunkLoaders#122]
**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, 1.2.8a-forge

**Are you using OptiFine?:** Never

**Description of the Bug**
When starting the server, chunkloaders dont work. I know this cause I have a redstone line which says hi with a command block every 5 secs. When I place a single chunk loader, and break it again, Everything starts functioning again (redstone and commandblock). This stays on until the server is restarted.

I have tried with servercore and both the "Default" and "optimized" configs they provide and in both is the same.

**Steps to Reproduce**
- Install ServerCore and Chunkloaders
- Place a chunkloader (in this case is from another player in the server)
- Set-up a clock to a command-Block that just prints "hi"
- restart server
- enter and turn the clock on.
- leave and it stops printing.
- turn the chunkloader off and then on.
- It works again

**Screenshots**
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/78743681/d47c128e-be66-4354-b722-702f3e4a840e)
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/78743681/f5e49f14-d5fb-4beb-8884-0207dc3a254b)

**Comment by SuperMartijn642** [comment]
On Forge, all the chunk loading is handled through Forge's chunk loading API, including loading chunks again when the server is restarted. It not working when ServerCore is installed, would suggest they break Forge's chunk loading API.
Hence, I think the issue is on ServerCore's side.

**Comment by SuperMartijn642** [comment]
Indeed this seems to have been an issue with ServerCore which has now been fixed (https://github.com/Wesley1808/ServerCore/issues/95).
