### ISSUE TITLE
Need for Fabric (Minecraft 1.21 and +)

### ISSUE THREAD

**Issue by Vitokhv** [SuperMartijn642/ChunkLoaders#126]
Need for Fabric 0.16.0 (Minecraft 1.21 and +)

**Comment by SuperMartijn642** [comment]
?

**Comment by Twizzle-B** [comment]
+1  
I believe they mean they would like the mod to be updated for the new 1.21 version of Minecraft :)

**Comment by SuperMartijn642** [comment]
Probably yeah, although creating an issue for it isn't gonna make them be updated sooner
