### ISSUE TITLE
[Crash] Crash when exiting server

### ISSUE THREAD

**Issue by Yuchenjimmy** [SuperMartijn642/ChunkLoaders#127]
**Version Info**
- Minecraft 1.21
- Fabric loader 0.15.11
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

**Are you using OptiFine?:**
No, but with iris.

**Steps to Reproduce**
1. Exit server

**Detals**
The client will crash instantly after clicking quit button, but this problem doesn't occur when leaving single player worlds.

**Crash report (~/logs/latest.log)**
- The game crashed whilst mouseclicked event handler
- Error: java.lang.NullPointerException: mouseClicked event handler
- Code: -1
[latest.log](https://github.com/user-attachments/files/16349484/latest.log)
[crash-2024-07-24_01.47.44-client.txt](https://github.com/user-attachments/files/16352531/crash-2024-07-24_01.47.44-client.txt)

**Comment by SuperMartijn642** [comment]
I don't see anything related to Chunk Loaders in the crash log and you seem to be using quite a lot of mods. Are you sure this is caused by Chunk Loaders?

**Comment by Yuchenjimmy** [comment]
Yes, I've done some tests. ~~If I remove chunk loader from the my self-hosting server, the client will no longer crash.~~

==Update==
This problem may be related to SuperMartijn642's Core Lib mod, if it's installed on the server, the client will prompt saving a game, then crash. After removing it, I can now leave the server as usaul.

**Comment by SuperMartijn642** [comment]
Okay thanks. I just left for vacation and I also just have a lot to catch up on, so it will likely be a while before I look into the issue.

**Comment by Yuchenjimmy** [comment]
No problem, hope you have a nice vacation! I also found this problem doesn't occur on Paper server, so I would switch to it as a temporal workaround.

**Comment by SuperMartijn642** [comment]
Hmm Paper can't load Fabric mods, you did install the mods on the server as well right?

**Comment by Yuchenjimmy** [comment]
LOL so that's the reason that the client didn't crash. Yes I did install all dependencies, corelib, config, and chunk loaders. Removing chunk loader alone can't fix the problem, after removing corelib the client won't crash anymore.

**Comment by Yuchenjimmy** [comment]
**Problematic**

_Server side_
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

_Client side_
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

=======

**Problematic**

_Server side_
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

_Client side_
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

=======

**Problematic**

_Server side_
- SuperMartijn642's Core Lib 1.1.17

_Client side_
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

=======

**No problem**

_Server side_
- SuperMartijn642's Config Lib 1.1.8

_Client side_
- Chunk loader 1.2.8
- SuperMartijn642's Core Lib 1.1.17
- SuperMartijn642's Config Lib 1.1.8

**Comment by SuperMartijn642** [comment]
This is an issue with Elytra Trims. The author of Elytra Trims is working on a fix though, you can find the relevant issue here https://github.com/kikugie/elytra-trims/issues/67
Thank you for reporting the issue of course 🙂
