### ISSUE TITLE
[Crash] No startup

### ISSUE THREAD

**Issue by UnAwareAi** [SuperMartijn642/ChunkLoaders#129]
**Version Info**
- Minecraft, 1.16.5 FTB Ultimate Anniversary Edition
- Chunk Loaders, 1.2.8a

**Are you using OptiFine?:** No

**Steps to Reproduce**
added jar file to mod folder and server crashes on startup

**Crash report (~/logs/latest.log)**
[crash-2024-07-31_21.28.55-fml.txt](https://github.com/user-attachments/files/16448787/crash-2024-07-31_21.28.55-fml.txt)

**Comment by UnAwareAi** [comment]
I realized that I did not have the corelib or configlib jar files installed with chunk loaders, but could not get a compatible version with the version of tesseract that is already installed on this modpack.

**Comment by SuperMartijn642** [comment]
Just use the latest version of everything 🤔

**Comment by UnAwareAi** [comment]
I got it all working through some trial and error. Thanks, I'm a bit new to this all.
