### ISSUE TITLE
[Crash] Disconnect when trying to grab chunk loader items

### ISSUE THREAD

**Issue by extendow** [SuperMartijn642/ChunkLoaders#131]
**Version Info**
- Minecraft, 1.21
- Chunk Loaders, 1.2.8 for Fabric

**Are you using OptiFine?:** No

**Steps to Reproduce**
Hello, there is a problem with the chunks loader mod. It works flawlessly in the single world, but as for the server, there are some problems. I play on the hosting, I put this mod there. It is displayed in the creative, but as soon as I try to take it, the server breaks the connection with me

**Crash report (~/logs/latest.log)**
...

**Comment by extendow** [comment]
When I try to put an item from the mod into an inventory cell, this message writes to me: The connection is lost 

When I take an item from the creative and throw it out into the world, I write this: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraftset_creative_mode_slot*

**Comment by SuperMartijn642** [comment]
Looking at the logs you send me once again, the server isn't even a Fabric server. You are running a paper server.
You need to install Chunk Loaders both on the client and on the server.
