### ISSUE TITLE
[Bug] ...not working like at all

### ISSUE THREAD

**Issue by felicia1the1goat** [SuperMartijn642/ChunkLoaders#132]
**Version Info**
- fabric, 1.21
- Chunk Loaders, 1.2.8

**Are you using OptiFine?:** nope

**Description of the Bug**
the mod displays in modmenu but the items are just not loading like i cant craft them i cant get them in the creative inventory and i also cant /give them im in a singleplayer flat world btw

**Steps to Reproduce**
...

**Screenshots**

![image](https://github.com/user-attachments/assets/304f7548-36b1-49bb-8565-7a9c0d3e4b0a)
![image](https://github.com/user-attachments/assets/49611072-8ab9-4bcc-afca-3d8d3b1462b8)

![image](https://github.com/user-attachments/assets/9126f1ff-b80e-483d-8cb9-ddfe5243610c)
![image](https://github.com/user-attachments/assets/c50fd393-caf0-43b0-9317-3d6d2b2e0c6f)

**Comment by SuperMartijn642** [comment]
Chunk Loaders appears to work just fine:

![image](https://github.com/user-attachments/assets/5b2392e7-9b90-4780-8cda-e7bbb07d07dc)

Can you share the `logs/latest.log` logs?
Can you reproduce the issue without any other mods? If so, could you narrow down what other mods are needed to reproduce the issue?

**Comment by felicia1the1goat** [comment]
[64f166a2-72c9-4b94-bb24-e0439ac4da2c-master.log](https://github.com/user-attachments/files/16998405/64f166a2-72c9-4b94-bb24-e0439ac4da2c-master.log)
ill try it w/o any other mods in a sec but sodium is hardcoded into lunars fabric mods idk if thats a problem tho

**Comment by SuperMartijn642** [comment]
Ah if you are using Lunar Client, please report the issue to them. They use a custom fork of Fabric Loader which breaks mods. There's nothing I can do about that.
