### ISSUE TITLE
[Bug] No Map Loads

### ISSUE THREAD

**Issue by Zenornia** [SuperMartijn642/ChunkLoaders#138]
Minecraft 1.21.3 Fabric Loader with latest SuperMartijn642's Config Lib & SuperMartijn642's Core Lib 

Chunk Loader 1.21.3 works great however when i place down a Chunk Loader and open the map, all tiles appear as pure black.

I do not have any texture packs and can not find the reason why this is, so it is hard for me to know where im selecting.

I have notice no other bug like this has been posted and wondering if anyone has had this issue and/or knows a possible resolution to fix this issue.

Thanks

**Comment by SuperMartijn642** [comment]
Please fill in the template. What version of Chunk Loaders are you using?

Are you using any other mods? Other people have reported this issue on Discord and it was caused by ImmediatelyFast. Are you also using ImmediatelyFast and if so, does the issue go away if you disable that mod?

**Comment by J0v3n** [comment]
I have a quit similar bug. I reloaded the game and only loaded chunks by the mod are loaded. If i placed down a chunloader and loaded the missing chunks there were coming back. I deactivated the mod but then no chunks are loading. F3+A wasn´t working either
Hope you can help.

**Comment by SuperMartijn642** [comment]
@J0v3n I am not sure what you mean. Are you talking about the chunk loader gui map? If not, that's unrelated to this issue and please create a separate issue for it.

**Comment by Zenornia** [comment]
> Please fill in the template. What version of Chunk Loaders are you using?
> 
> Are you using any other mods? Other people have reported this issue on Discord and it was caused by ImmediatelyFast. Are you also using ImmediatelyFast and if so, does the issue go away if you disable that mod?

ImmediatelyFast was the issue, Thank you for the assistance!
