### ISSUE TITLE
[Crash] ...

### ISSUE THREAD

**Issue by R3e** [SuperMartijn642/ChunkLoaders#139]
**Version Info**
- Minecraft, ...
- Chunk Loaders, ...

1.21.1
-Chunk Loaders and dependencies

**Are you using OptiFine?:** ...
no

**Steps to Reproduce**
install mods on the fabric server and trying to start it 

**Crash report (~/logs/latest.log)**
picture
![2024-11-23 22_29_14-Proxmox-VE - Proxmox Virtual Environment](https://github.com/user-attachments/assets/48d377a7-0373-491f-9178-4beb33212d62)

apperently i dont have fabric on a fabric server

**Comment by SuperMartijn642** [comment]
Fabric API is the part that's missing. You can find it on CurseForge or Modrinth.

**Comment by R3e** [comment]
Ok thanks worked fine and thanks for quick support
