### ISSUE TITLE
[Bug] Can't join server with Chunk Loaders

### ISSUE THREAD

**Issue by taza325** [SuperMartijn642/ChunkLoaders#18]
**Version Info**
- Minecraft 1.16.5

**Description of the Bug**
when i load the on the server my game freeze then im disconnected. that happens every time when i try to join server.

**Steps to Reproduce**
set up chunk loader on server then leave. now you can't join - yey

**Comment by SuperMartijn642** [comment]
Seems to work fine.

What version of Chunk Loaders are you using?

What message do you get when you try to join?
And could you upload the server log file from you tried to join?

**Comment by SuperMartijn642** [comment]
Feel free to comment here with more info and I'll reopen the issue.
