### ISSUE TITLE
[Feature] Disable player's chunk loaders after inactivity

### ISSUE THREAD

**Issue by bigenergy** [SuperMartijn642/ChunkLoaders#2]
Hey. I suggest adding the function to disable the chunkloader when the player is not on the server for 3-7 days
There is such a function in ChickenChunks and The Weirding Gadget

**Comment by bigenergy** [comment]
@SuperMartijn642 pls add(

**Comment by Tander** [comment]
+1

**Comment by Bobbysx** [comment]
+1
Just came here to suggest this :)

**Comment by SuperMartijn642** [comment]
I will be adding a way to disable a player's chunk loaders after some time of inactivity. Just don't know when.

**Comment by ghost** [comment]
Please also add a setting for duration. I'd like to be able to have loaders only active when players are logged in.

**Comment by SuperMartijn642** [comment]
The duration will be configurable in the config file.

**Comment by SuperMartijn642** [comment]
As of Chunk Loaders 1.2.0 you can now set an inactivity duration after which a player's chunk loaders will be disabled.
Thank you for the suggestion!
