### ISSUE TITLE
Are peaceful mobs supposed to disappear when they're in a loaded chunk?

### ISSUE THREAD

**Issue by suchipi** [SuperMartijn642/ChunkLoaders#22]
**Question**

I've noticed that cows and sheep eventually disappear when I put a chunk loader on them. Is that normal? Do you know why it happens?

I want to chunkload the ranch so the babies can grow up while I'm away.

**Comment by SuperMartijn642** [comment]
As far as I know both cows and sheep shouldn't despawn in vanilla.
The Chunk Loader works the same way as the vanilla /forceload command. If they don't despawn with /forceload, but do with a chunk loader it is an issue with Chunk Loaders. Otherwise it is probably another mod messing with it.

**Comment by suchipi** [comment]
Thanks! I tested again and they aren't despawning anymore, so it must have been something else. I appreciate the response!
