### ISSUE TITLE
Chunk loaders don't appear in-game as a recipe and can't be crafted

### ISSUE THREAD

**Issue by stephanknotek** [SuperMartijn642/ChunkLoaders#24]
**Version Info**
- Minecraft, 1.17
- Chunk Loaders, 1.1.7

**Description of the Bug**
Chunk loaders simply aren't in my game. No errors or anything when adding them to my server world. I added the jar to my server mods folder and my local mods folder and it simply isn't there, even if I use the recipe command or look for it in REI.

**Steps to Reproduce**
Installed the mod and ran the game.

**Screenshots**

**Comment by SuperMartijn642** [comment]
REI is a Fabric mod right? Chunk Loaders is only available for Forge.

**Comment by stephanknotek** [comment]
> REI is a Fabric mod right? Chunk Loaders is only available for Forge.

oh gotcha! Ok, I thought it was for Fabric. Yeah REI and all of my current mods are running Fabric. Sorry for the confusion. If you're ever willing to make the leap to Fabric, I'd be so happy to use your mod if you were willing/able to make a port or switch entirely. I know development is hard work so I just wanted to say thank you for your hard work regardless:)

**Comment by SuperMartijn642** [comment]
As of right now, I have no plans to port my mods to Fabric, but maybe one day 🙂

**Comment by 1oglop1** [comment]
@SuperMartijn642 I got caught by that as well, it would be good if you can mention it on curseforge page that the mode is for Forge only
