### ISSUE TITLE
[Crash] Mod loading has failed

### ISSUE THREAD

**Issue by bblewitt** [SuperMartijn642/ChunkLoaders#25]
**Version Info**
- Minecraft, 1.17.1
- Chunk Loaders, 1.1.7-mc1.17
- Forge version: 37.0.33

**Steps to Reproduce**
Made a test modpack and installed chunkloaders mod and booted up the game and it shows 2 messages:

Chunk Loaders encountered an error during the common_setup event phase
Chunk Loaders encountered an error during the error event phase

**Crash report (~/logs/latest.log)**
The crash report is from my own modpack but also double checked it on a test modpack with it only installed and still the same error.

https://pastebin.com/3mVjiiqE

**Comment by SuperMartijn642** [comment]
Forge 37.0.31 had a breaking change. Until I update it, you could downgrade to Forge 37.0.30 or lower.

**Comment by bblewitt** [comment]
Okay no worries, thanks for letting me know.

**Comment by SuperMartijn642** [comment]
I fixed it now in version 1.1.7a.

Thank you for reporting the issue!
