### ISSUE TITLE
[Bug] Chunk loader not working for villager breeding and food grinder

### ISSUE THREAD

**Issue by FishyDish** [SuperMartijn642/ChunkLoaders#26]
I have a chunk loader at my auto food grinder and villager breeder on a server so even when everyone is offline they should still work, but when i go back nothing has changed, not sure if it is because they are in modded biomes from biomes o' plenty

**Comment by SuperMartijn642** [comment]
I assume your auto food grinder depends on mob spawning. Mobs only spawn around players, not just when a chunk is loaded.
You might want to check out [Scarecrows' Territory](https://www.curseforge.com/minecraft/mc-mods/scarecrows-territory), it allows mobs to spawn around scarecrows which you can place.

I have no clue if villager breeding requires a player nearby, as far as I can find online, it does not.
The villagers might look for nearby job stations or villages, so you might just need to load a bigger area.

Anyways, if things work with the `/forceload` command but not with Chunk Loaders, it's a bug with Chunk Loaders.
If things also don't work with `/forceload`, they probably require other factors apart from just the chunk being loaded.

**Comment by SuperMartijn642** [comment]
Feel free to comment and I will reopen the issue.
