### ISSUE TITLE
[Question] AI functionality in loaded chunks

### ISSUE THREAD

**Issue by UMayhan** [SuperMartijn642/ChunkLoaders#29]
**Question**
Hello, 

I am playing Minecolonies (creating your own colony with AI citizens) mod in SP and due to Minecraft itself even if I've placed chunk loader seems that AI do not work if I am far enough

Is there any options to ask chunk loaders keep AI functionality if I far away? 

thanks in advance

**Comment by SuperMartijn642** [comment]
Chunk loaders should work the same as the vanilla `/forceload` command, apart from also doing random ticks. Could you test if it works with the `/forceload` command?
If it does, it is probably a bug in Chunk Loaders.
If it does not, I might be able to add it as a feature, but I would have to look into if that is possible and not just hardcoded on entities.

**Comment by SuperMartijn642** [comment]
Feel free to comment and I will reopen the issue.
