### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by ghost** [SuperMartijn642/ChunkLoaders#3]
My game always crashes when a chunkloader is used or placed.
I use the version 1.16.3 from Forge Recommended and the Chunkloader-Version "chunkloaders-1.1.0a-mc1.16.3".
Here is the crash report:
[hs_err_pid2331.log](https://github.com/SuperMartijn642/ChunkLoaders/files/5487380/hs_err_pid2331.log)

Thanks for fixing :)

**Comment by SuperMartijn642** [comment]
This is an Java VM crash report, I need the Minecraft ones, either in the folder crash-reports, both crash-***-client.txt and crash-***-server.txt, or I need the latest.log in the logs folder.

I can see in the Java VM report that you're using Java 1.8.0-74, although it shouldn't be an issue, maybe a newer version can fix the problem. Currently the latest is Java 1.8.0-271.

**Comment by ghost** [comment]
Ah ok.
Here are the "latest.log" and the "debug.log" from the "logs"-folder.
There were no files in the "crash-reports"-folder.
Thanks for the answer!


[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/5494548/latest.log)
[debug.log](https://github.com/SuperMartijn642/ChunkLoaders/files/5494554/debug.log)

**Comment by SuperMartijn642** [comment]
It seems like this is a JVM crash and might be caused by an OpenGl error, other than that I can't find any hints to what the problem could be.
I tested it on the Forge version you are using and everything seems to work fine.

I have some question to narrow down the issue.
1. Did you have any mods installed apart from Chunk Loaders? I don't see anything in the reports, but just to be sure.
2. Does your game run fine with just Forge and without any mods?
3. When exactly does the game crash? For example, like you mentioned when you place a chunk loader.
4. Does the game always crash or just some times?

**Comment by ghost** [comment]
I also tried again with the latest Java version.
It crashed again.
Logs:
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/5494879/latest.log)
[debug.log](https://github.com/SuperMartijn642/ChunkLoaders/files/5494880/debug.log)


Your questions:

1. I have uninstalled all other mods.

2. Forge has always run well so far. Also with mods it has always worked very well.

3. The game crashes when I click on the chunkloader.
    The map image appears briefly and then java crashes.
    If I just place the chunkloader, minecraft continues to run normally.

4. ALWAYS when I click on the chunkloader the game crashes!

**Comment by ghost** [comment]
Now I am very confused:
I tried it on a Windows pc and it works fine.
Apparently it is because of my Mac.

Too bad that it does not work on my MacBook.
I cannot explain it to me.

**Comment by SuperMartijn642** [comment]
It could be a difference in OpenGl compatibility between the graphics of the two computers. Sadly, I don't own a Mac, so I can't test on it.
I will have a look at the code to see if there's something obvious which might cause problems on some graphics cards.

**Comment by ghost** [comment]
Ok, thanks!
Would be happy if you can write a post here, if you found a problem.

**Comment by ghost** [comment]
I have also tried it on my server.
Strangely enough only the minecraft on my computer crashes when using a chunkloader, but not the server!?

If I just place the chunkloader but don't click it, it will load the chunk and the game will not crash. Only when I click on it, the game crashes on my computer.

If you like I can also send you a video recording of it...

**Comment by SuperMartijn642** [comment]
When you right click  on a chunk loader it open a screen client side, but nothing happens on the server. The map is only rendered on the client. Since the map seems to be the problem, only the client thus crashes.

**Comment by ghost** [comment]
Thanks for the info!
Hope that you will find the error :)

**Comment by SuperMartijn642** [comment]
I uploaded a new version 1.1.0b where I changed some of the OpenGL related code.
Could you test if that fixes the problem?

**Comment by ghost** [comment]
Wonderful!
I have tried it on the latest Java version
and it works perfectly.
I am very happy that they have fixed the bug.

Thanks for your quick feedback :-)


Will you fix it for the older versions too?
I do not need it.
I am just asking.

**Comment by SuperMartijn642** [comment]
Great that that fixed it!

I will also add these changed to 1.14, 1.15 and the other 1.16 versions. 1.12 already had this implementation.

Thank you for reporting the issue!
