### ISSUE TITLE
[Question] Plans for Fabric version?

### ISSUE THREAD

**Issue by Snoddas76** [SuperMartijn642/ChunkLoaders#30]
**Question**
Are there any plans to implement this mod for Fabric?

**Comment by SuperMartijn642** [comment]
Currently, I have no plans to port my mods to Fabric. This has a couple of reasons:
- I already know Forge, so in the time I would have to spend learning Fabric, I could also just make more mods for Forge
- Forge has a larger player base than Fabric (at least as of now)
- I already support 5 versions, 1.12, 1.14, 1.15, 1.16, and 1.17 on Forge, for all my mods. Every time I add features, I have to do it for all those versions. If I also support Fabric, that would add yet another version I have to maintain that is a lot different from the others

I have nothing against Fabric, but right now I just don't feel like it is worth the time I would invest into it

**Comment by Snoddas76** [comment]
Thanks for the reply :)
