### ISSUE TITLE
[Feature] Add Fabric or Forge to the CurseForge Page to indicate whether the mod is Fabric or Forge

### ISSUE THREAD

**Issue by coldReactive** [SuperMartijn642/ChunkLoaders#35]
On the [CurseForge page](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders), it isn't indicated anywhere (at least not in firefox) what modloader the mod uses. I had to look through what modpacks had this mod in, in order to find out this is a Fabric Mod, and thus won't work on Forge.

In addition, it would be nice to find out an alternative to this for forge is, since the "Literally" Chunk Loader mod is also for fabric.

**Comment by SuperMartijn642** [comment]
![image](https://user-images.githubusercontent.com/12382965/147411756-e8d1571a-0d28-4029-99e6-bb76ef9ea036.png)
If you click on the file you want to use, CurseForge shows what modloader it is for.

> In addition, it would be nice to find out an alternative to this for forge is, since the "Literally" Chunk Loader mod is also for fabric.

I don't understand this sentence.

**Comment by coldReactive** [comment]
I'm not sure how a modpack or two, which are Fabric, managed to get this into their modpack then. (Check your mod's dependents list in relations.)
