### ISSUE TITLE
[Bug] Portal Guns stop working when Chunk Loaders is installed

### ISSUE THREAD

**Issue by Yeddy7** [SuperMartijn642/ChunkLoaders#36]
- Minecraft, 1.12.2
- Chunk Loaders, 1.1.7

was using portal gun mod and after i added chunk loaders the portal guns stopped working

**Comment by SuperMartijn642** [comment]
I installed the following mods for Minecraft 1.12:
- chunkloaders-1.1.7-mc1.12
- iChunUtil-1.12.2-7.2.2
- PortalGun-1.12.2-7.1.0
- supermartijn642configlib-1.0.9-mc1.12

From my testing, the portal gun works just fine.
What exactly doesn't work about the portal gun and what are the steps to reproduce the issue?

**Comment by Yeddy7** [comment]
My bad i had a item in my off hand not allowing it to work, mod works fine
