### ISSUE TITLE
[Crash] Crashes game on startup

### ISSUE THREAD

**Issue by Scunningham03** [SuperMartijn642/ChunkLoaders#39]
**Version Info**
- Minecraft, 1.18.1 with Forge
- Chunk Loaders, 1.1.8 mc-1.18.1

**Steps to Reproduce**
Start the game

**Crash report (~/logs/latest.log)**
...
[crash-2022-01-08_21.17.00-fml.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/7834457/crash-2022-01-08_21.17.00-fml.txt)

**Comment by SuperMartijn642** [comment]
Chunk Loaders requires my core and config libraries.
![Screenshot_20220109-075005](https://user-images.githubusercontent.com/12382965/148672271-3ebb7853-f277-4ceb-9de4-9d82c04b3272.png)
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib
https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib
