### ISSUE TITLE
Chunk loaders deselect chunks to load on world restart

### ISSUE THREAD

**Issue by EvergreenSystems** [SuperMartijn642/ChunkLoaders#42]
**Version Info**
- Minecraft 1.18.1
- Chunk Loaders 1.1.7
- Forge 39.0.9

**Description of the Bug**
When a world is closed and reopened chunk loaders will sometimes deselect and therefore unload all chunks within their area of effect

**Steps to Reproduce**
Place chunk loader of any variety, close and reopen the world

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
This has been fixed in Chunk Loaders 1.1.7b for Minecraft 1.18.
