### ISSUE TITLE
[Question] ...Chunk Loaders

### ISSUE THREAD

**Issue by driftirl** [SuperMartijn642/ChunkLoaders#43]
**Question**
...
can someone please help i am wondering does Chunk Loaders load mobs from mob spawners while u are not in the chunk?if this does its not working for me so can someone please help

**Comment by SuperMartijn642** [comment]
Chunk Loaders only keep the chunk loaded. Mob spawners being active doesn't depend on the chunk being loaded, it depends on whether there's a player within 24 blocks of it.

I do have another mod called [Scarecrows' Territory](https://www.curseforge.com/minecraft/mc-mods/scarecrows-territory) which keeps spawners active if you place a scarecrow near them.

**Comment by driftirl** [comment]
thank you so much for your help this is exactly what i need thank you so much again

**Comment by driftirl** [comment]
is there a way to chance the tic speed of the rate that they spawn at?

**Comment by SuperMartijn642** [comment]
Nope, it just keeps the spawner active like a player would.
