### ISSUE TITLE
Cannot Craft Basic Chunk Loader

### ISSUE THREAD

**Issue by numeralnathan** [SuperMartijn642/ChunkLoaders#44]
I have Minecraft 1.18.1.  I am running PaperMC on the server.  I am running Fabric on the client.  I put the Chunk Loaders 1.1.9 jar file into the client and server's mods directory.  

I started both.  I cannot craft a basic chunk loader.  I used this recipe on a crafting table.

https://github.com/SuperMartijn642/ChunkLoaders/blob/1.18/src/main/resources/data/chunkloaders/recipes/basic_chunk_loader.json

How do I get the chunk loaders mod working?  Please add installation instructions in your readme.

**Comment by SuperMartijn642** [comment]
Chunk Loaders is a mod for Forge.
PaperMC cannot load mods at all and Fabric can only load fabric mods 🤔

**Comment by numeralnathan** [comment]
:'(  Can you specify that this is a Forge mod in your readme?  Can you make a mod for Fabric?  Can you suggest an existing mod for Fabric?

**Comment by SuperMartijn642** [comment]
If click on the file you want to use on CurseForge it will show you whether the mod is for Fabric or for Forge.

No, as of right now I'm not gonna make Chunk Loaders for Fabric.

I don't play with Fabric, so I don't know any alternatives.
