### ISSUE TITLE
[Feature] Display useful map in the nether (now displaying only the top level bedrock)

### ISSUE THREAD

**Issue by DevPGSV** [SuperMartijn642/ChunkLoaders#45]
**Is your feature request related to a problem? Please describe.**
When using a chunkloader in the nether and opening the GUI, this is the map:

![image](https://user-images.githubusercontent.com/5631093/151337591-c6b0e2f9-5008-4507-b9fd-891571f6cfdb.png)

**Describe the solution you'd like**

It would be nice if somehow the map shown in the nether is made from the Y level vertical chunk where the chunk loader is.
Here is a picture taken from [JourneyMap](https://www.curseforge.com/minecraft/mc-mods/journeymap), taken where the chunkloader is located, as an example:

![image](https://user-images.githubusercontent.com/5631093/151337981-37db9e16-a835-437b-8e4a-e463517d761c.png)

**Comment by SuperMartijn642** [comment]
I changed it so in any dimension which has a ceiling, the map show blocks at the current y-level instead of the top of the world.

It is available now in Chunk Loaders version 1.2.0.
Thank you for the suggestion!
