### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by BraveCaperCat** [SuperMartijn642/ChunkLoaders#51]
**Question**
Does this mod work on the client side only?

**Comment by SuperMartijn642** [comment]
No... No clue how this would work on the client-side only, it adds new blocks, items, and functionality, all of which the server would have no knowledge of it is only installed on the client.

**Comment by BraveCaperCat** [comment]
Ok! it's just that i think FTB Chunks works on the client side, and it force loads chunks, i would of installed it if i knew which mod it was in, This mod saved me!
