### ISSUE TITLE
Is this mod for Fabric or Forge? [Question] ...

### ISSUE THREAD

**Issue by SebastianDevus** [SuperMartijn642/ChunkLoaders#53]
I know it might be a stupid question, but i couldn't find anything in the mod page indicating the modloader. If possible, could you also add some indication if its forge or fabric too?

**Comment by SuperMartijn642** [comment]
Chunk Loaders is only available for Forge.
CurseForge will show you if you click on the file you want to use.
![image](https://user-images.githubusercontent.com/12382965/161430191-4b54f36a-1235-484a-9738-9579d1bd76f5.png)
