### ISSUE TITLE
[Bug] ... cant mine up chunkloaders

### ISSUE THREAD

**Issue by Vadewolf** [SuperMartijn642/ChunkLoaders#56]
**Version Info**
- Minecraft, 1.18.2
- Chunk Loaders, 1.2.0 -forge-mc1.18

**Are you using OptiFine?:** nope

**Description of the Bug**
place down chunkloader but need to upgrade it and it just vanishes when mined

**Steps to Reproduce**
craft any chunkloader place down try to mine and lose chunkloader

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Seems I messed up the loot table generator in 1.16 and then for some reason fixed it again in 1.19.

Anyways, it's fixed now in Chunk Loaders 1.2.0a for 1.16, 1.17, and 1.18.
Thank you for reporting the issue!
