### ISSUE TITLE
Chunk not loaded

### ISSUE THREAD

**Issue by MinoCraft** [SuperMartijn642/ChunkLoaders#58]
Hello, 

I've updated ChunkLoaders version 1.1.12 to 1.2.0a and since this update chunks seems to be not loaded with chunkloaders.
Chunkloading is the mod goal, it's not a random feature of your mod ^^" For now, I'll continue to use 1.1.12.

Have a good day ;)

**Version Info**
- MineCraft 1.18.2, Forge 41.1.19
- Chunk Loaders 1.2.0a-forge-mc1.18

**Comment by SuperMartijn642** [comment]
Are these just the chunks that were still loaded from before the 1.2.0 update or are these chunks you loaded after claiming the chunk loader blocks?

**Comment by MinoCraft** [comment]
Loaded before update. After claiming, I've saw the new GUI and I've deleted claimed chunk to claim again. Leave zone and test and nothing happen when I've saw in an Ender Chest for example.
Also, I've tested with a new one. Destroy the old and place a new  CL. There is the same issue =/

**Comment by bigenergy** [comment]
> Hello,
> 
> I've updated ChunkLoaders version 1.1.12 to 1.2.0a and since this update chunks seems to be not loaded with chunkloaders. Chunkloading is the mod goal, it's not a random feature of your mod ^^" For now, I'll continue to use 1.1.12.
> 
> Have a good day ;)
> 
> **Version Info**
> 
> * MineCraft 1.18.2, Forge 41.1.19
> * Chunk Loaders 1.2.0a-forge-mc1.18

![image](https://user-images.githubusercontent.com/17977139/179419781-597d4095-48a5-47cc-9d2f-4625f7a894af.png)
incorrect forge version?

**Comment by MinoCraft** [comment]
I can't update Forge version ! There are somes mistakes and I've reported too. It work nice for me with 1.1.12. 
So, if the 1.2.0a not work for me just because wrong Forge version, you can close the ticket. 
For now I don't update mod anymore. It's not a problem for me. 
Sorry for the inconvenient =/

**Comment by SuperMartijn642** [comment]
Ah seems it might indeed be caused by an older Forge version. Forge 40.1.58 fixes the chunk loading issues. The older version of Chunk Loaders still works because it only partially used Forge's system.

I have now published Chunk Loaders 1.2.0b for 1.18 to set the minimum Forge version to 40.1.58 for people running into the same issue.
Thank you for reporting the issue!
