### ISSUE TITLE
[Question] There is a way to use Chunk Loader 1.1.2 on supermartijn642configlib 1.1.5 forge?

### ISSUE THREAD

**Issue by Dustynzzz** [SuperMartijn642/ChunkLoaders#60]
**Question**
Forge Version: 41.0.45
Minecraft Version: 1.19
Supermartijn642configlib 1.1.5
Chunkloader Version: 1.2.0
My question is; is possible to use this version of Chunk loader mod on 1.1.5 of the config lib on Minecraft 1.19?
I want to use this mod on my modpack but dont work with this version of supermartijn642configlib 1.1.5, i cant upgrade forge because a lot of mod wouldn't work.

**Comment by SuperMartijn642** [comment]
Nope, the restriction for the newer Forge version is there for a reason. I'm not going to change the mod to just work with an older version of Forge 🤔
That's just backwards.

Sadly, you'll just to wait for those other mods to update.
