### ISSUE TITLE
1.18.1 Server startup error 

### ISSUE THREAD

**Issue by wadiv76** [SuperMartijn642/ChunkLoaders#61]
Missing language javafml version [40,) wanted by chunkloaders-1.2.0c-forge-mc1.18.jar, found 39

Mod file: chunkloaders-1.2.0c-forge-mc1.18.jar

The following additional files are installed:
supermartijn642configlib-1.1.6-forge-mc1.18.jar
supermartijn642corelib-1.0.19-forge-mc1.18.jar

I may be mistaken, but isn't javafml version 40 usually referencing Forge for 1.18.2?

**Comment by tobizor** [comment]
Same Problem for us, seems to be the wrong javafml version redirected.

**Comment by SuperMartijn642** [comment]
Forge 40.1.58 has an important fix for Forge's loaded chunk managing system. This fix is only available for 1.18.2.

> I may be mistaken, but isn't javafml version 40 usually referencing Forge for 1.18.2?

So indeed, you need 1.18.2. I changed the marked versions on CurseForge as well now, to only be 1.18.2.

**Comment by tobizor** [comment]
Any chance to get this back on 1.18.1? Still need a Chunkloader on this Version :)

**Comment by SuperMartijn642** [comment]
Nope sorry, the fix is essential for the functionality of the chunk loaders and bypassing Forge's system causes compatibility issues with other mods. Also, is there any reason not to upgrade to 1.18.2?
