### ISSUE TITLE
[Crash] The game crashed whilst exception in server tick loop

### ISSUE THREAD

**Issue by jopamaster12** [SuperMartijn642/ChunkLoaders#63]
[crash-2022-08-06_17.46.43-server.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/9275255/crash-2022-08-06_17.46.43-server.txt)

**Comment by SuperMartijn642** [comment]
This doesn't look like it is caused by Chunk Loaders. Can you reproduce the issue with just Chunk Loaders and it's dependencies?
Also please fill in the report template next time.

**Comment by jopamaster12** [comment]
I delete Optifine and it helps me
