### ISSUE TITLE
[Bug] ...crash with chunkloaders

### ISSUE THREAD

**Issue by Vadewolf** [SuperMartijn642/ChunkLoaders#66]
**Version Info**
- Minecraft, ...
- Chunk Loaders, ...

**Are you using OptiFine?:** ...
heck no
**Description of the Bug**
...open the UI using C and it crashes

**Steps to Reproduce**
...
[crash-2022-08-27_22.39.03-client.txt](https://github.com/SuperMartijn642/ChunkLoaders/files/9439054/crash-2022-08-27_22.39.03-client.txt)

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Fixed now in version 1.2.3.

Thank you for reporting the issue!
