### ISSUE TITLE
[Question] can you edit the requirement for ChunkLoaders

### ISSUE THREAD

**Issue by nightmare3007** [SuperMartijn642/ChunkLoaders#67]
**Question**
...
i have try to install the mod in my costom modpack but it will shut down and will not inform me why.
i had to try added it to a test forge to found out i need core lib and Config Lib to add the mod to my modpack

**Comment by SuperMartijn642** [comment]
These requirements are already properly set in `mods.toml` and also on CurseForge and Modrinth.
