### ISSUE TITLE
[Bug] inactivityTimeout parameter not working as it should

### ISSUE THREAD

**Issue by bigenergy** [SuperMartijn642/ChunkLoaders#69]
**Version Info**
- Minecraft: 1.18.2
- Chunk Loaders: 1.2.2

**Are you using OptiFine?:** no

**Description of the Bug**
inactivityTimeout parameter not working as it should.
When the server is restarted, 
`Set<UUID> activePlayers = new LinkedHashSet<>();` - cleared...
Data should be stored in a more secure place, since, for example, a player may not log in for more than 1-2 days, and the downloader must work.

**Comment by SuperMartijn642** [comment]
Not sure what you mean. All data is saved to disk, including when a player was last online. When the server restarts this is just loaded from disk again as you can see here https://github.com/SuperMartijn642/ChunkLoaders/blob/0e2d245392f5b95df769b13229863cadb69353dd/src/main/java/com/supermartijn642/chunkloaders/capability/PlayerActivityTracker.java#L93

**Comment by SuperMartijn642** [comment]
Closing this as the original issue is invalid, since the timeout data is already saved and loaded again between restarts.
