### ISSUE TITLE
[Bug] Cant craft

### ISSUE THREAD

**Issue by CuboneCubone** [SuperMartijn642/ChunkLoaders#7]
I cant get the crafting recipes to work in single player or on my server. ive only tested the first one because that first item is required to craft the 4 other ones. I am also running tweakaroo with no issues if that may cause problems?

**Comment by SuperMartijn642** [comment]
What Minecraft and Chunk Loaders version are you using? (The first two lines of the bug report template)

**Comment by CuboneCubone** [comment]
sorry ive never used github before i didn't even know there was a template. i'm running fabric 1.16.4 with the most recent version of the mod

**Comment by SuperMartijn642** [comment]
No worries, mostly put that there so when other people see it they know to use the bug template.

Anyways, Chunk Loaders is only available for Forge and won't even be loaded if you are using Fabric.
