### ISSUE TITLE
[Bug] dispensers doesnt work as intended 

### ISSUE THREAD

**Issue by ourehae** [SuperMartijn642/ChunkLoaders#71]
**Version Info**
- Minecraft, 1.19.2
- Chunk Loaders, 1.2.2

**Are you using OptiFine?:** no (playing with create mod)

**Description of the Bug**
i was building a vanilla nether star farm and of course i needed the dispensers to place sculls on soul sand but after a few attempts i realized that they just making the noise but nothing happens and after some time of trying i figured out that it's beacause of chunkloaders since i tried to remove every mod in mod folder and try to use the dispenser 

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Chunk Loaders has nothing to do with dispenser behaviour.
