### ISSUE TITLE
[Question] Dependencies

### ISSUE THREAD

**Issue by GlydetheSurfer** [SuperMartijn642/ChunkLoaders#73]
**Question**
Why aren't the dependencies for the mod in the description on curseforge? I had to waste my time launching the game because I forgot what they were. I knew there were dependencies because I had installed this mod before, but I had forgotten what they were called.

**Comment by DreaminBoi** [comment]
there's a list of dependencies when you click on a file and the relations tab

**Comment by SuperMartijn642** [comment]
CurseForge already shows the dependencies when you click on the file you want to use:
![image](https://user-images.githubusercontent.com/12382965/207057015-24014eb0-c227-4410-a5a6-c0b419e69f15.png)
Or if you just click on the 'relations' tab like @DreaminBoi said:
![image](https://user-images.githubusercontent.com/12382965/207057137-59c9ae94-1b78-4ec3-baed-97c16b463926.png)
