### ISSUE TITLE
[Feature] Waterlogging support

### ISSUE THREAD

**Issue by magiruuvelvet** [SuperMartijn642/ChunkLoaders#8]
It would be nice if the chunk loaders could be waterlogged when placed under water. Is this possible with the current implementation?

**Comment by SuperMartijn642** [comment]
Yes, I will be adding the ability to waterlog the chunk loaders.

**Comment by SuperMartijn642** [comment]
I added it now in version 1.1.5 for Minecraft 1.14, 1.15, and all the 1.16 versions.

Thanks for the suggestion!

**Comment by magiruuvelvet** [comment]
Thanks for implementing this^^ This adds some more beauty to underwater structures.
