### ISSUE TITLE
[Crash] Fabric version crashes on startup

### ISSUE THREAD

**Issue by SplendidAlakey** [SuperMartijn642/ChunkLoaders#81]
**Version Info**
- Minecraft, 1.19.4
- Chunk Loaders, 1.2.3

**Are you using OptiFine?:** no

**Steps to Reproduce**
Simply install the mod and its dependencies, then run the game.

**Crash report (~/logs/latest.log)**
https://gist.github.com/SplendidAlakey/ab59bb220f99f3dc8e6a277a4e2a489c

**Comment by SuperMartijn642** [comment]
I fixed it now in Chunk Loaders version 1.2.3a.

Thank you for reporting the issue!
