### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by laserboy07** [SuperMartijn642/ChunkLoaders#83]
**Version Info**
- Minecraft, Fabric 1.19.4
- Chunk Loaders, 1.2.3a-fabric-mc1.19
**Are you using OptiFine?:** No, Sodium

**Description of the Bug**
Whenever I load a chunk the game drastically drops the FPS, slowly returning back to normal.

**Steps to Reproduce**
Load a chunk using a chunk loader, and reload the world.

**Screenshots**
...
I'm the same one from the crash report, I re-downloaded the mods and now it is much better, tho it does still drop the FPS to around 20 when loading a chunk.
After a while it gets better. and most of the times back to normal.
Also, I found out that when a chunk loader is placed, when joining a world the chunks reload slow and takes about 20 seconds to return to normal, and the FPS meanwhile is also low and slowly returning to normal.

**Comment by laserboy07** [comment]
After further testing, the bug is very inconsistent and the times takes to get back to normal varies, but when trying to join a world with a chunk loader the loading time is still much longer than without a chunk loader.

**Comment by SuperMartijn642** [comment]
Not sure why this is in a separate issue from #82.
