### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by GoriYT** [SuperMartijn642/ChunkLoaders#86]
**Version Info**
- Minecraft, 1.12
- Chunk Loaders, basic and single chunk loaders

**Are you using OptiFine?:** yes

**Description of the Bug** when i am on the overworld the chunkloader on the nether does not load at all

**Steps to Reproduce** place a chunkloader activated than go to other dimension

**Comment by ghost** [comment]
Can Confirm, happens to me too. Version 1.12.2, Optifine installed.
Chunks are unloaded when the Dimension is switched.

**Comment by SuperMartijn642** [comment]
It seems to be working fine:

https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/98d203f3-b7c8-4221-966b-adc73ef9ed81

If this issue still occurs, please open a new issue and provide the requested version information.
