### ISSUE TITLE
[Bug]  not working on 1.19.4 optifineforge

### ISSUE THREAD

**Issue by LakshayGMZ** [SuperMartijn642/ChunkLoaders#87]
**Version Info**
- Minecraft, 1.19.4
- Chunk Loaders, [This](https://www.curseforge.com/minecraft/mc-mods/chunk-loaders/files/4356876)

**Are you using OptiFine?:** yes

**Description of the Bug**
cant craft chunk loaders with the recipe provided

**Steps to Reproduce**
...

**Screenshots**
...

**Comment by SuperMartijn642** [comment]
Seems to work just fine.
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/12382965/2674fd8f-57b6-4cc3-942e-a814e10317b1)

**Comment by LakshayGMZ** [comment]
Can you tell me what you used for instal, direct curseforge or downloaded
manually. if manually, what config and libs did you install?

**Comment by SuperMartijn642** [comment]
I just installed the file you linked plus the two dependencies, my core and config libraries.

**Comment by LakshayGMZ** [comment]
Ok I tested it in single player survival and it works, but not in
multiplayer servers.

**Comment by SuperMartijn642** [comment]
Did you install it on the server?

**Comment by LakshayGMZ** [comment]
No. Is it server sided mod? I want any client sided

**Comment by SuperMartijn642** [comment]
How do you expect to place a block which does not exist on the server
