### ISSUE TITLE
[Bug] Spawner

### ISSUE THREAD

**Issue by KEDPLOL** [SuperMartijn642/ChunkLoaders#88]
**Version Info**
- Minecraft, 1.12.2
- Chunk Loaders, 1.2.3 for Forge 1.12

**Are you using OptiFine?:** yes

**Description of the Bug**
Chunk Loaders Won't load a spawner in a specific Chunk without players load near the spawner, recently tried in an Ultimate Chunk Loader

**Screenshots**
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/136044881/43263f56-79a1-4897-ba23-3a4a4b2b927b)
  
  
![image](https://github.com/SuperMartijn642/ChunkLoaders/assets/136044881/3c8bae85-a85d-4b69-a3ac-3529f9c649ff)

**Comment by SuperMartijn642** [comment]
Spawners are only active when a player is within 16 blocks of it. This has nothing to do with chunk loading.
