### ISSUE TITLE
[Bug] cant register required supermartijn642corelib

### ISSUE THREAD

**Issue by Sokraa** [SuperMartijn642/ChunkLoaders#92]
- Minecraft, 1.16.5
- Chunk Loaders, 1.2.4

Optifine: yes

>tried to launch the mod for the first time
>two error msgs: ,,requires supermartijn642corelib 1.1.0 or above" and ,,requires supermartijn642corelib 1.6.0 or above"
>downloaded 1.1.10 - error w/1.6.0. or above still shows (the one w/1.1.0 doesnt show)
>downloaded 1.1.9 same error
>downloaded 1.1.6 same error

**Comment by SuperMartijn642** [comment]
> two error msgs: ,,requires supermartijn642corelib 1.1.0 or above" and ,,requires supermartijn642corelib 1.6.0 or above"

There is no version 1.6.0 of my core library. Please upload the log or share the exact message.

**Comment by Sokraa** [comment]
im sorry, i just realised that im dumb and just couldnt read that error corectly.. everythings working nicely

**Comment by SuperMartijn642** [comment]
Ah no worries, glad it works. I'll close the issue then.

**Comment by Sokraa** [comment]
I read that in way it looked for me that supermartijn642corelib and supermartijn642configlib are the same.. sorry my mistake

**Comment by DamnUi** [comment]
> I read that in way it looked for me that supermartijn642corelib and supermartijn642configlib are the same.. sorry my mistake
Just experienced the same thing im glad i looked through the solved issues
