### ISSUE TITLE
[Crash] Incompatability with "Out of Sight", crash when rendering a chunk loader

### ISSUE THREAD

**Issue by kackalack** [SuperMartijn642/ChunkLoaders#93]
**Version Info**
- Minecraft, 1.18.2
- Chunk Loaders, ...

**Are you using OptiFine?:** No

**Steps to Reproduce**
Place any chunk loader with "Out of Sight" installed
**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/ChunkLoaders/files/11965739/latest.log)

**Comment by SuperMartijn642** [comment]
Caused by Out of Sight. This has already been reported to Out of Sight and I have submitted a pull request to fix it https://github.com/Corosauce/OutOfSight/pull/14.
For now, just don't use Out of Sight I guess 🤷‍♂️
