### ISSUE TITLE
Mob spawner and mobtrap radius active

### ISSUE THREAD

**Issue by luwdev-br** [SuperMartijn642/ChunkLoaders#94]
hello good morning, I would like to ask a question regarding the mod, I did some tests and it cannot load mobpawner and mob trap, would this be something that can be added? all these the player needs to be within a certain radius of distance to work, would it be something to be added to the mod?
by the way great mob, I loved it

**Comment by SuperMartijn642** [comment]
Mob spawners being active has nothing to do with chunk loading. And keeping mob spawners active in any loaded would cause a lot of lag and lead to people unintentionally keeping spawners active.

If you want something to keep spawners active and prevent mobs from despawning, you can use Scarecrows' Territory https://legacy.curseforge.com/minecraft/mc-mods/scarecrows-territory
