### ISSUE TITLE
[Bug] ...

### ISSUE THREAD

**Issue by TheGamingDogYT7** [SuperMartijn642/ChunkLoaders#96]
**Version Info**
- Minecraft, 1.19.2
- Chunk Loaders, 1.2.5

**Are you using OptiFine?:** No

**Description of the Bug**
I make a Mob farm placed a Chunk loader down, selected the chunks I wanted loaded, came back afew hours later and there isnt any new drops. The chunk loader didn't keep the chunk loaded (Since i came back it started to work again)

**Steps to Reproduce**
Im not sure as I didn't do anything

**Screenshots**
[...](https://prnt.sc/8gLpServNB2K)

**Comment by TheGamingDogYT7** [comment]
Sorry I just found out its not the mods fault haha

**Comment by SuperMartijn642** [comment]
No worries, I will close the issue then
