### ISSUE TITLE
[Bug] Chunkloader stop working when going through Endportal and back

### ISSUE THREAD

**Issue by MickNick98** [SuperMartijn642/ChunkLoaders#99]
**Version Info**
- Minecraft, 1.20.1
- Chunk Loaders, 1.2.5
- Fabric API, 0.85.0

**Playing on Server?:** Yes.

**Are you using OptiFine?:** No.

**Description of the Bug**
Whenever I go through the End Portal and back to the Overworld, the Chunkloaders in the Overworld stop working.

**Steps to Reproduce**
When I click on a Chunkloader it say's "0 Chunks loaded". As far as I can say the Chunkloaders in the Nether and the End seems still working after you went back. When you go to the Nether and back to the Overworld this issue isn't present.

**Temporary Solution**
Reconnect to the Server to "restart" the Chunkloaders.

**Screenshots**
(Not really helpful but maybe more clear)

_before going through Endportal:_
![2023-08-14_11 16 22](https://github.com/SuperMartijn642/ChunkLoaders/assets/142214703/bbd4175d-85db-43ec-bf44-95b0930533da)

_after going back to the Overworld:_
![2023-08-14_11 16 47](https://github.com/SuperMartijn642/ChunkLoaders/assets/142214703/a8735343-1d6e-4f04-a2b8-60163cee9f52)

_after reconnect to the Server:_
![2023-08-14_11 17 06](https://github.com/SuperMartijn642/ChunkLoaders/assets/142214703/10f92417-bddb-4584-816a-e5b58b0acd3c)

**Comment by SuperMartijn642** [comment]
Ah seems Fabric's player dimension change event doesn't get called when going through an end portal or when respawning when killed, since those are a bit of a special case.
Should be fixed now in Chunk Loaders version 1.2.7. Thank you for reporting the issue!
